# Use postgres/postgres for postgres credentials: DATABASE_URL=postgres://postgres:postgres@127.0.0.1:5432/postgres
version: "3.1"

networks:
  NO_SQL_INJECTION_TEST:
    driver: bridge

services:
  postgres:
    container_name: "nosql-injection-postgres-test"
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data-test:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - NO_SQL_INJECTION_TEST
  bitnami_mongodb:
    container_name: "nosql-injection-mongodb_test"
    image: bitnami/mongodb:5.0.2
    restart: always
    environment:
      MONGODB_ROOT_PASSWORD: password123
      MONGODB_USERNAME: user123
      MONGODB_PASSWORD: password123
      MONGODB_DATABASE: ts-express
    ports:
      - 27017:27017
    networks:
      - NO_SQL_INJECTION_TEST

  redis:
    container_name: "nosql-injection-redis-test"
    image: "bitnami/redis:6.0.8"
    environment:
      REDIS_PASSWORD: password123
    ports:
      - 6379:6379
    networks:
      - NO_SQL_INJECTION_TEST
